---
#- debug:
#    msg: "Connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Upgrade Systems
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Upgrade Older Systems
      package:
        name: "*"
        state: latest
      when: >
        (ansible_distribution == "CentOS" and
        ansible_distribution_version != "8.2") or
        (ansible_distribution == "Ubuntu" and
        ansible_lsb.description != "Ubuntu 18.04.5 LTS")
...

# ... add dots once tested