---
- debug:
    msg: "Connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"


dpkg-reconfigure openssh-server


# ... add dots once tested