---
- debug:
    msg: "Connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

# ... add dots once tested

- name: test
  hosts: all
  gather_facts: true
  become: true
  handlers:
    - name: restart_sshd
  service:
  name: sshd
  state: restarted
  tasks:
    - name: install
  package:
  state: latest
  name:
    - bash-completion
    - vim
    - nano
    - name: Create tux user
  user:
  name: tux
  state: present
  password: "{{ 'Password1' | password_hash('sha512') }}"
  update_password: on_create
  shell: /bin/bash
    - name: Edit SSHD Config
  lineinfile:
  path: /etc/ssh/sshd_config
  regexp: '^PasswordAuthentication '
  insertafter: '#PasswordAuthentication'
  line: 'PasswordAuthentication yes'
  notify: restart_sshd
    - name: Add sudo rights for tux
  copy:
  dest: /etc/sudoers.d/tux
  content: "tux ALL=(root) NOPASSWD: ALL"
  backup: true