---
- debug:
    msg: "Connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: App to install
  hosts: all
  tasks:
    - name: install apache ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache centos
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == "Centos" 