---
- name: Play to patch only CentOS systems
  hosts: all
  become: true

  tasks: 
  - name: Patch CentOS systems
    yum:
      name: httpd
      state: latest
    when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")


   #https://github.com/PacktPublishing/Practical-Ansible-2/blob/master/Chapter%204/condition2.yml
   
   