---
- name: sshd
  hosts: all
  gather_facts: false
  handlers:
    - name: restart_sshd
      systemd:
        name: sshd.service
        state: restarted
  
  tasks:

    - name: enable sshd
      systemd:
        name: sshd
        enabled: true
        state: started

     - name: No Root
       lineinfile:
         path: /etc/ssh/sshd_config
         regexp: '^PermitRootLogin'
         insertafter: '#LoginGraceTime'
         line: 'PermitRootLogin no'
      notifiy: restart_sshd

  