---
- name: SELinux | Include {{ ansible_os_family }} specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - vars/{{ ansible_os_family|lower }}.yml
    - vars/default.yml

# tasks file for /home/linuks/linux/roles/ssh