--- # Test_Playbook.yml
- name: test play in #roles / tasks / main.yml 
  hosts: linux
  gather_facts: true

  tasks:
    - debug:
        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
... 
# tasks file for /home/linus/ansible/playbooks/linux/roles/ssh