--- 
- hosts: all
  gather_facts: true

  tasks:
    - debug:
        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"


# tasks file for /home/linuks/linux/roles/ssh