- name: Create /var/log/journal if it does not exist
  file:
    path: /var/log/journal
    state: directory
    owner: root:systemd-journal
    group: foo
    mode: '2755'

# tasks file for /home/linuks/linux/roles/ssh