---
- hosts: localhost
  become: true
  tasks:
  - name: install ms rpm key
    rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - name: Create a directory if it does not exist
    file:
      path: /etc/yum.repos.d
      state: directory
      mode: '0755'
  - name: Change file ownership, group and permissions
    file:
      path: /etc/yum.repos.d/vscode.repo
      owner: linus
      state: touch

  - name: Ansible Insert multiple lines using blockinfile
    blockinfile:
      dest: /etc/yum.repos.d/vscode.repo
      block: |
        [code]
        name=Visual Studio Code
        baseurl=https://packages.microsoft.com/yumrepos/vscode
        enabled=1
        gpgcheck=1
        gpgkey=https://packages.microsoft.com/keys/microsoft.asc
      backup: yes
  - name: install visualcode
    yum:
      name: code
      state: latest

# tasks file for /home/linuks/linux/roles/ssh