---
diable direct root login
pam_securetty can restrict login to "secure" terminals
secure terminals listed in /etc/securetty
empty file means root cannot login anywhere
*non-existent file means root can log in everywhere
pam module doesn't effect ssh 
Disable root login through sshd /etc/ssh/sshd_config: PermitRootLogin no