---
- name: manage user
  host: all
  become: true
  gather_facts: false
  tasks:
    - name: create users w input task
      user:
        name: "{{ user_name }}"
        password: "{{ 'Password1'| password_hash('sha512','AS343') }}"
        update_password: on_create
      when: user_create == 'yes'

    - name: delete users w input task
      user:
        name: "{{ user_name }}"
        state: absent
        remove: true
      when: user_create == 'no'
# add
# ansible-playbook -e "user_create=yes user_name=bob" create_user_w_input_linux.yml
# remove
# ansible-playbook -e "user_create=no user_name=bob" create_user_w_input_linux.yml