---
- name: create arnold user
  host: all
  become: true
  gather_facts: false
  tasks:
    - name: create user task
      user:
        name: arnold

    - name: sudo access for user
      copy: 
        dest: /etc/sudoers.d/arnold
        content: 'arnold ALL(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %sbin

    - name: ssh key
      authorized_key:
      user: arnold
      state: present
      manage_dirs: true
      key: "{{ lookup( 'file', '/home/linus/.ssh/id_rsa.pub') }}"

# ansible-playbook arnold_user.yml