---
- debug:
    msg: "Connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: install visualcode
  yum:
    name: code
    state: latest
    
# ... add dots once tested