---
- debug:
    msg: "Connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Copy file 
  ansible.builtin.copy:
    src: /etc/ssh/ssh_host_* #/srv/myfiles/foo.conf
    dest: /etc/ssh/old_keys #/etc/foo.conf




#- name: copy default keys
 # become: true
#  ansible.builtin.shell: mv /etc/ssh/ssh_host_* /etc/ssh/old_keys/


# ... add dots once tested