---
- debug:
    msg: "Connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
  
- name: Create a directory if it does not exist
  file:
    path: /etc/yum.repos.d
    state: directory
    mode: '0755'
... 