---
- debug:
    msg: "I cjk am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Add the user 'splunker' with a bash shell, appending the group 'admins' to the user's group
  user:
    name: splunker
    state: present
    password: kilger001
    shell: /bin/bash
    groups: wheel
    append: yes

