---
- name: install php
  package:
    name: php
    state: latest
  notifiy: restart_web

- name: index.php
  copy:
    src: index.php
    destination: '/var/www/html/index.php'
    mode: '640'
    group: "{{ web_group }}"