---
- debug:
    msg: "Connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Add the user 'linus' with a bash shell, appending the group 'admins' to the user's group
  user:
    name: linus
    state: present
    password: P@ssw0rd
    shell: /bin/bash
    groups: admin
    append: yes


# ... add dots once tested