---
- debug:
    msg: "Connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Add the user 'puppetier' with a bash shell, appending the group 'admins' to the user's group
  user:
    name: puppetier
    become: true
    state: present
    password: kilger001
    shell: /bin/bash
    groups: wheel
    append: yes

