---

dependencies: []

galaxy_info:
  role_name: 'systemd_journald'
  author: 'Adfinis AG'
  description: 'Configure systemd-journald'
  company: 'Adfinis AG'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - systemd
    - journald
