---
- name: Install apt cockpit package
  become: true
  apt: 
    name: cockpit
    state: latest
    update_cache: yes
    cache_valid_time: 3600
...


# ... add dots once tested

# fails on kali-00 3/10/2021
# success us-01 3/10/2021