---
- name: kali tools update
  hosts: debian
  become: true
  roles:
#    - kali_tools_setup
    - debian_git_setup
    - centos_sudo-passwdless_setup
    - kali_move-default-ssh_setup
    # .... add dots once tested

    