--- # Test_Playbook.yml
- hosts: all
  gather_facts: true
  become: true
  tasks:
    - debug:
        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

#    - name: Show facts available on the system
#      ansible.builtin.debug:
#        var: ansible_facts

  roles:
 #   - kali_apt-grant root_setup.yml
     - kali_tools_setup
 #   - test_role.yml
 #   - kali_mv-default-ssh_setup
... 
#end