--- # Test_Playbook.yml
- name: test play in roles 
  hosts: linux
  gather_facts: true

  tasks:
    - debug:
        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
... 