---
- debug:
    msg: "Connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: ensure git is installed
  yum:
    name: tmux
    state: latest
- hosts: ubuntuserver20-04
  become: yes
  name: Update Hostname on Ubuntu
  package: apt
  state: present

# ... add dots once tested