---
- debug:
    msg: "Connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: ensure git is installed
#  hosts: debian #ubuntuserver20-04
#  become: yes
  ansible.builtin.package:
    name:
      - httpd
      - git
    state: latest


#  apt:
#    name: git
#    state: latest
    
# ... add dots once tested